### ISSUE TITLE
See comment.

### ISSUE THREAD

**Issue by jpieczar** [ALittleLessThanMediocre/ALittleLessThanMediocre#1]
See title.

**Comment by ALittleLessThanMediocre** [comment]
self referential logic detected, closing issue before infinite loop initiated.

**Comment by jpieczar** [comment]
830 days later...

**Comment by ALittleLessThanMediocre** [comment]
missed the 730 landmark, had to wait 100 days to round it off nicely again...

**Comment by jpieczar** [comment]
Understandable. Have a good day...
